name: Build pymatgen wheel for Python 3.13 on Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Upgrade pip and install build tools
        run: |
          python -m pip install --upgrade pip build wheel setuptools

      - name: Build wheel
        run: python -m build

      - name: Upload wheel as artifact
        uses: actions/upload-artifact@v4
        with:
          name: pymatgen-wheel-py313
          path: dist/*.whl
